<a href="https://colab.research.google.com/github/crce9830ecs-lang/aiml_labs/blob/main/ML_LAB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

4-08 **NumPy**

In [11]:
#creating arrays
import numpy as np
arr = np.array([4,5,6,3,2,1])
print(arr)

b = np.arange(1,11) #give a range and then function will create an array
print(b)

c = np.linspace(0,1,5)
print(c)    #0: The starting point of the sequence.1: The end point of the sequence (included by default).5: The total number of elements to generate.

[4 5 6 3 2 1]
[ 1  2  3  4  5  6  7  8  9 10]
[0.   0.25 0.5  0.75 1.  ]

In [14]:
# matrix operation
a =np.array(([1,2],
             [3,4]))
b =np.array(([2,2],
             [4,4]))
print(a+b)
print(a-b)
print(a*b) #element wise multiplication
print(a@b) # matix multiplication

[[3 4]
 [7 8]]
[[-1  0]
 [-1  0]]
[[ 2  4]
 [12 16]]
[[10 10]
 [22 22]]

In [27]:
#assignment
# weather data of july days in udupi,
# - find hottest and clodest day
# - ang temp
# - dates above 35 deg cel
import numpy as np

weather = np.array([
    [1, 26], [2, 28], [3, 28], [4, 29], [5, 30],
    [6, 30], [7, 30], [8, 30], [9, 31], [10, 30],
    [11, 30], [12, 30], [13, 30], [14, 31], [15, 31],
    [16, 30], [17, 27], [18, 29], [19, 29], [20, 27],
    [21, 29], [22, 26], [23, 29], [24, 30], [25, 29],
    [26, 29], [27, 30], [28, 28], [29, 29], [30, 30],
    [31, 30]
])

index = np.argmin(weather[:,1])
date = weather[index, 0]
temp = weather[index, 1]
print(f"hottest day is on {date} with a temperature of {temp}")

index = np.argmax(weather[:,1])
date = weather[index, 0]
temp = weather[index, 1]
print(f"coldest day is on {date} with a temperature of {temp}")

avg = np.mean(weather[:,1])
print(f"the avg temp is {avg}")

if ((weather[:,1]) > 35).all():
  print((weather[:,1]))

hottest day is on 1 with a temperature of 26
coldest day is on 9 with a temperature of 31
the avg temp is 29.193548387096776

**Pandas**

In [28]:
import pandas as pd
student = {
    "Name": ["Elita", "Sania", "Novak", "Lennon"],
    "Age" : [21,23,7,10],
    "Marks": [70,80,90,100]

}
df = pd.DataFrame(student)
print(df)

     Name  Age  Marks
0   Elita   21     70
1   Sania   23     80
2   Novak    7     90
3  Lennon   10    100

In [32]:
from sklearn.datasets import load_iris
iris = load_iris(as_frame=True)
print(iris.data)
df = iris.frame
df.head(10)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
5,5.4,3.9,1.7,0.4,0
6,4.6,3.4,1.4,0.3,0
7,5.0,3.4,1.5,0.2,0
8,4.4,2.9,1.4,0.2,0
9,4.9,3.1,1.5,0.1,0

In [35]:
df.info()

df.describe()

df.shape

df.columns

df.tail(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 6.0 KB

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2